baseURL = "https://pythonbiellagroup.github.io/ModernPythonDevelopment/"
languageCode = "en-us"
title = "Python Biella Group Learning Page"
theme = "hugo-theme-learn"
publishDir = "docs"
defaultContentLanguageInSubdir= true

pygmentsUseClasses = true
pygmentsCodeFences = true
enableRobotsTXT = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/PythonBiellaGroup/ModernPythonDevelopment/tree/master/content"
author = "Andrea Guzzo"
description = "Python Biella Group Reference Website and Guides"
disableBreadcrumb = false
showVisitedLinks = true
disableLandingPage = false
disableNextPrev = false
disableAssetsBusting = false
themeVariant = "blue"
version = "v0.1"
landingPageURL = "/ModernPythonDevelopment/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[Languages]
[Languages.en]
landingPageURL = "/ModernPythonDevelopment/"
landingPageName = "<i class='fas fa-home'></i> Redirect to Home"