baseURL = "https://pythonbiellagroup.github.io/ModernPythonDevelopment/"
languageCode = "en-us"
title = "Python Biella Group Learning Page"
theme = "hugo-theme-learn"
publishDir = "docs"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false
editURL = "https://pythonbiellagroup.github.io/ModernPythonDevelopment/blob/master/content/"
author = "Andrea Guzzo"
description = "Python Biella Group Reference Website and Guides"
showVisitedLinks = true
disableLandingPage = false
disableNextPrev = true
themeVariant = "blue"
version = "v0.1"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[Lanugages]
[Lanugages.en]
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Redirect to Home"